name: POSIX Conformance CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  posix-conformance-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup test data
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/testlog
          openssl ecparam -name prime256v1 -genkey -noout -out ${{ github.workspace }}/testlog/test-ecdsa-priv.pem
          openssl ec -in ${{ github.workspace }}/testlog/test-ecdsa-priv.pem -pubout > ${{ github.workspace }}/testlog/test-ecdsa-pub.pem
          echo "WORKSPACE=${{ github.workspace }}" > ${{ github.workspace }}/env
          cat ${{ github.workspace }}/env

      - name: Spin up POSIX tesseract CI test
        shell: bash
        run: |
          echo "Launching POSIX tesseract"

          export CT_LOG_PUBLIC_KEY=$(openssl ec -pubin -inform PEM -in ${{ github.workspace }}/testlog/test-ecdsa-pub.pem -outform der | base64 -w 0)
          export UID
          export GID
          export WORKSPACE="${{ github.workspace }}"
          
          # Ensure cleanup happens on exit
          trap "docker compose -f ./cmd/tesseract/posix/ci/docker-compose.yml logs; docker compose -f ./cmd/tesseract/posix/ci/docker-compose.yml down" EXIT

          # Start all services detached
          # Tesseract, Remote Root Server, and Hammer
          echo "Starting all services detached..."
          ls -la ${{ github.workspace }}/testlog
          
          docker compose -f ./cmd/tesseract/posix/ci/docker-compose.yml \
            --env-file="${{ github.workspace }}/env" up -d
          docker compose -f ./cmd/tesseract/posix/ci/docker-compose.yml logs

          echo "Waiting for hammer to exit..."
          HAMMER_EXIT_CODE=$(docker wait hammer)
          echo "Hammer exited with $HAMMER_EXIT_CODE"
          
          if [ "$HAMMER_EXIT_CODE" != "0" ]; then
          echo "FAILED: Hammer failed."
            exit 1
          fi
          echo "Hammer ran successfully."

          # Check Remote Root Server exit code
          SERVER_EXIT_CODE=$(docker wait remote_root_server)
          echo "Remote Root Server exited with $SERVER_EXIT_CODE"
          
          if [ "$SERVER_EXIT_CODE" != "0" ]; then
             echo "FAILED: Remote Root Server failed (exit code $SERVER_EXIT_CODE)."
             exit 1
          fi
          echo "Remote Root Server verification successful."

      - name: fsck the log
        shell: bash
        run: |
          echo "Launching fsck"

          export CT_LOG_PUBLIC_KEY=$(openssl ec -pubin -inform PEM -in ${{ github.workspace }}/testlog/test-ecdsa-pub.pem -outform der | base64 -w 0)
          docker build -f ./cmd/fsck/Dockerfile -t fsck:latest .
          docker run \
            --mount "type=bind,src=${{ github.workspace }}/testlog,dst=/testlog" \
              fsck:latest \
                --monitoring_url=file:///testlog \
                --origin=example.com/test-ecdsa \
                --public_key=${CT_LOG_PUBLIC_KEY} \
                --N=5
